/**
 * TIXORA 100 EVENT DATASET
 * Covering 20 Major Indian Cities and 9 diverse event categories:
 * - 25 Movies (Telugu, Hindi, Tamil, Malayalam, Kannada, Bengali, Marathi, Punjabi, Gujarati, Odia, Assamese)
 * - 20 Concerts / Live Music (Rock, Pop, Classical, EDM, Sufi, Carnatic, Bollywood, Tollywood, Jazz, Indie, Rap, Retro)
 * - 10 Sports (Cricket, Football, Badminton, Tennis, Kabaddi, Table Tennis)
 * - 10 Comedy / Stand-up Specials
 * - 10 Theatre / Drama
 * - 10 Cultural / Festivals
 * - 5 Conferences / Summits
 * - 5 College Events
 * - 5 Family / Entertainment
 * Total: Exactly 100 Events distributed across all 20 cities (5 events per city).
 */

const baseImages = {
  movie: [
    'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1574267432553-4b4628081c31?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?auto=format&fit=crop&w=800&q=80',
  ],
  concert: [
    'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80',
  ],
  sports: [
    'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?auto=format&fit=crop&w=800&q=80',
  ],
  comedy: [
    'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1527224857830-43a7acc85260?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
  ],
  theatre: [
    'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80',
  ],
  festival: [
    'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80',
  ],
  conference: [
    'https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80',
  ],
  college: [
    'https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80',
  ],
  family: [
    'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
  ],
};

const rawEvents = [
  // ===================== 1. MUMBAI (5 events) =====================
  {
    name: 'Jawan: Special IMAX Director Cut Screening',
    description: 'Special premiere screening with 4K laser projection and Atmos surround sound. High-octane action spectacle.',
    category: 'Movie',
    genre: 'Action/Thriller',
    language: 'Hindi',
    city: 'Mumbai',
    venue: 'PVR INOX Palladium, Lower Parel',
    daysAhead: 3,
    time: '19:00',
    duration: '2h 45m',
    price: 450,
    totalSeats: 40,
    image: baseImages.movie[0],
  },
  {
    name: 'Mumbai Philharmonic: Bollywood Symphonic Night',
    description: 'A 60-piece orchestra performing reimagined classics of R.D. Burman, A.R. Rahman, and Shankar-Ehsaan-Loy.',
    category: 'Concert',
    genre: 'Symphony / Bollywood',
    language: 'Hindi',
    city: 'Mumbai',
    venue: 'NCPA Jamshed Bhabha Theatre, Nariman Point',
    daysAhead: 6,
    time: '19:30',
    duration: '2h 15m',
    price: 1200,
    totalSeats: 50,
    image: baseImages.concert[0],
  },
  {
    name: 'Mumbai City FC vs Mohun Bagan: ISL Super Clash',
    description: 'High stakes Indian Super League showdown under floodlights with electrifying stadium atmosphere.',
    category: 'Sports',
    genre: 'Football',
    language: 'English/Hindi',
    city: 'Mumbai',
    venue: 'Mumbai Football Arena, Andheri Sports Complex',
    daysAhead: 10,
    time: '20:00',
    duration: '2h 00m',
    price: 600,
    totalSeats: 50,
    image: baseImages.sports[0],
  },
  {
    name: 'Bandra Comedy Showcase: All-Star Unfiltered',
    description: 'Top Indian stand-up comedians perform fresh observational comedy and hilarious crowd work sets.',
    category: 'Comedy',
    genre: 'Stand-up',
    language: 'Hinglish',
    city: 'Mumbai',
    venue: 'The Habitat, Khar West',
    daysAhead: 4,
    time: '20:30',
    duration: '1h 30m',
    price: 499,
    totalSeats: 30,
    image: baseImages.comedy[0],
  },
  {
    name: 'Mughal-E-Azam: The Broadway Musical Extravaganza',
    description: 'Feroz Abbas Khan’s award-winning theatrical spectacle featuring 70 live kathak dancers and original compositions.',
    category: 'Theatre',
    genre: 'Historical Musical',
    language: 'Hindi/Urdu',
    city: 'Mumbai',
    venue: 'Nita Mukesh Ambani Cultural Centre (NMACC)',
    daysAhead: 14,
    time: '18:30',
    duration: '2h 30m',
    price: 1500,
    totalSeats: 60,
    image: baseImages.theatre[0],
  },

  // ===================== 2. DELHI (5 events) =====================
  {
    name: 'Dangal: 10th Anniversary Commemorative Screening',
    description: 'Celebrated sports drama back on the 70mm big screen with special director introduction and audience Q&A.',
    category: 'Movie',
    genre: 'Biographical Drama',
    language: 'Hindi',
    city: 'Delhi',
    venue: 'PVR Director’s Cut, Vasant Kunj',
    daysAhead: 5,
    time: '18:00',
    duration: '2h 40m',
    price: 650,
    totalSeats: 30,
    image: baseImages.movie[1],
  },
  {
    name: 'Delhi Sufi Nights: Nizami Bandhu Live Qawwali',
    description: 'Renowned Sufi masters Nizami Bandhu live in concert singing soulful Sufi poetry, Amir Khusro ghazals and qawwalis.',
    category: 'Concert',
    genre: 'Sufi / Qawwali',
    language: 'Urdu/Hindi',
    city: 'Delhi',
    venue: 'Kamani Auditorium, Copernicus Marg',
    daysAhead: 8,
    time: '19:00',
    duration: '2h 30m',
    price: 850,
    totalSeats: 40,
    image: baseImages.concert[1],
  },
  {
    name: 'Delhi Premier League T20 Finals',
    description: 'Thrilling cricket championship finale under the stadium floodlights with packed stands and fireworks.',
    category: 'Sports',
    genre: 'Cricket',
    language: 'Hindi/English',
    city: 'Delhi',
    venue: 'Arun Jaitley Cricket Stadium, Feroz Shah Kotla',
    daysAhead: 12,
    time: '19:30',
    duration: '3h 30m',
    price: 750,
    totalSeats: 50,
    image: baseImages.sports[1],
  },
  {
    name: 'Delhi International Arts & Heritage Fest',
    description: 'Classical dances, folk craft pavilions, artisan bazaars, and traditional North Indian culinary pavilions.',
    category: 'Cultural',
    genre: 'Cultural Heritage',
    language: 'Multilingual',
    city: 'Delhi',
    venue: 'India Habitat Centre, Lodhi Road',
    daysAhead: 15,
    time: '11:00',
    duration: '6h 00m',
    price: 300,
    totalSeats: 40,
    image: baseImages.festival[0],
  },
  {
    name: 'India Tech Leaders Conclave 2026',
    description: 'National summit bringing together CTOs, enterprise architects, and venture partners on AI infrastructure.',
    category: 'Conference',
    genre: 'Technology',
    language: 'English',
    city: 'Delhi',
    venue: 'Bharat Mandapam, Pragati Maidan',
    daysAhead: 18,
    time: '09:30',
    duration: '8h 00m',
    price: 1800,
    totalSeats: 50,
    image: baseImages.conference[0],
  },

  // ===================== 3. BENGALURU (5 events) =====================
  {
    name: 'Kantara: A Legend Re-imagined Dolby Atmos',
    description: 'Sensational coastal folklore epic presented with multi-channel Dolby Atmos sound and pristine master print.',
    category: 'Movie',
    genre: 'Folklore / Action',
    language: 'Kannada',
    city: 'Bengaluru',
    venue: 'PVR Vega City IMAX, Bannerghatta Road',
    daysAhead: 4,
    time: '18:45',
    duration: '2h 30m',
    price: 380,
    totalSeats: 40,
    image: baseImages.movie[2],
  },
  {
    name: 'Bangalore Indie Wave: Live Alt-Rock Fest',
    description: 'Featuring Thermal and a Quarter, Pineapple Express, and rising indie singer-songwriters under the open skies.',
    category: 'Concert',
    genre: 'Indie / Alt-Rock',
    language: 'English/Kannada',
    city: 'Bengaluru',
    venue: 'Jayabheri Silicon Arena, Electronic City',
    daysAhead: 9,
    time: '18:00',
    duration: '3h 30m',
    price: 899,
    totalSeats: 50,
    image: baseImages.concert[2],
  },
  {
    name: 'Pro Badminton Masters League: Bengaluru Round',
    description: 'Fast-paced badminton smash action featuring national champions and international shuttlers.',
    category: 'Sports',
    genre: 'Badminton',
    language: 'English',
    city: 'Bengaluru',
    venue: 'Kanteerava Indoor Stadium, Sampangi Rama Nagar',
    daysAhead: 13,
    time: '16:00',
    duration: '3h 00m',
    price: 450,
    totalSeats: 40,
    image: baseImages.sports[2],
  },
  {
    name: 'Ranga Shankara Festival: Kannada Contemporary Theatre',
    description: 'A powerful dramatic stage play interrogating modernization, urban living, and cultural roots.',
    category: 'Theatre',
    genre: 'Drama',
    language: 'Kannada',
    city: 'Bengaluru',
    venue: 'Ranga Shankara, JP Nagar',
    daysAhead: 7,
    time: '19:30',
    duration: '2h 00m',
    price: 300,
    totalSeats: 30,
    image: baseImages.theatre[1],
  },
  {
    name: 'IISc Pravega: National Science & Collegiate Fest',
    description: 'The flagship inter-collegiate festival celebrating cutting-edge engineering, robotics warfare, and science debate.',
    category: 'College Event',
    genre: 'Inter-College Tech & Arts',
    language: 'English',
    city: 'Bengaluru',
    venue: 'Indian Institute of Science Campus, Malleshwaram',
    daysAhead: 16,
    time: '10:00',
    duration: '7h 00m',
    price: 250,
    totalSeats: 40,
    image: baseImages.college[0],
  },

  // ===================== 4. HYDERABAD (5 events) =====================
  {
    name: 'RRR: Roar of Hyderabad Anniversary Screening',
    description: 'SS Rajamouli’s monumental Academy Award-winning epic shown on India’s largest IMAX projection screen.',
    category: 'Movie',
    genre: 'Epic / Action',
    language: 'Telugu',
    city: 'Hyderabad',
    venue: 'Prasads IMAX, NTR Gardens, Necklace Road',
    daysAhead: 2,
    time: '19:15',
    duration: '3h 05m',
    price: 450,
    totalSeats: 40,
    image: baseImages.movie[3],
  },
  {
    name: 'Tollywood Beats Live: DSP & Thaman Symphony',
    description: 'Massive concert celebrating Telugu chartbusters, electrifying choreography, and live percussion drums.',
    category: 'Concert',
    genre: 'Tollywood Night / Pop',
    language: 'Telugu',
    city: 'Hyderabad',
    venue: 'Gachibowli Athletic Stadium Grounds',
    daysAhead: 7,
    time: '18:30',
    duration: '3h 45m',
    price: 999,
    totalSeats: 60,
    image: baseImages.concert[3],
  },
  {
    name: 'Hyderabad Pro Tennis Open Finals',
    description: 'Championship baseline showdown featuring top ranked ATP players on hardcourt.',
    category: 'Sports',
    genre: 'Tennis',
    language: 'English',
    city: 'Hyderabad',
    venue: 'SAAP Tennis Complex, Fateh Maidan',
    daysAhead: 11,
    time: '17:00',
    duration: '2h 30m',
    price: 550,
    totalSeats: 40,
    image: baseImages.sports[3],
  },
  {
    name: 'Biryani & Chuckles: Telugu Stand-up Gala',
    description: 'Hyderabad’s top regional comedians presenting fresh Telugu stand-up and hilarious Hyderabadi dialect sketches.',
    category: 'Comedy',
    genre: 'Stand-up',
    language: 'Telugu/Dakhni',
    city: 'Hyderabad',
    venue: 'The Comedy Theatre, Jubilee Hills Road No 36',
    daysAhead: 5,
    time: '20:00',
    duration: '1h 45m',
    price: 399,
    totalSeats: 35,
    image: baseImages.comedy[1],
  },
  {
    name: 'Grand Magic & Illusions: Secrets of the Orient',
    description: 'Mind-boggling stage illusions, levitation acts, and interactive sleight-of-hand for family audiences of all ages.',
    category: 'Family',
    genre: 'Illusion / Magic',
    language: 'English/Hindi',
    city: 'Hyderabad',
    venue: 'Ravindra Bharathi Auditorium, Saifabad',
    daysAhead: 14,
    time: '16:30',
    duration: '2h 00m',
    price: 350,
    totalSeats: 40,
    image: baseImages.family[0],
  },

  // ===================== 5. CHENNAI (5 events) =====================
  {
    name: 'Ponniyin Selvan: Grand 70mm Special Experience',
    description: 'Mani Ratnam’s historical Chola dynasty magnum opus with remastered soundtrack and crystal visuals.',
    category: 'Movie',
    genre: 'Historical / Drama',
    language: 'Tamil',
    city: 'Chennai',
    venue: 'Sathyam Cinemas (PVR), Royapettah',
    daysAhead: 4,
    time: '18:30',
    duration: '2h 50m',
    price: 350,
    totalSeats: 40,
    image: baseImages.movie[4],
  },
  {
    name: 'Margazhi Carnatic Sangeetham: Aruna Sairam Live',
    description: 'Classical Carnatic vocal concert celebrating timeless ragas, devotional abhangs, and virtuosic mridangam accompaniment.',
    category: 'Concert',
    genre: 'Carnatic / Classical',
    language: 'Tamil/Sanskrit',
    city: 'Chennai',
    venue: 'The Music Academy, TTK Road, Alwarpet',
    daysAhead: 10,
    time: '18:15',
    duration: '2h 30m',
    price: 750,
    totalSeats: 45,
    image: baseImages.concert[4],
  },
  {
    name: 'Chennai Super Kabbadi Trophy: Knockout Stage',
    description: 'Breathtaking tackles, swift raids, and intense state-level kabaddi action with passionate roaring fans.',
    category: 'Sports',
    genre: 'Kabaddi',
    language: 'Tamil',
    city: 'Chennai',
    venue: 'Jawaharlal Nehru Indoor Stadium, Periamet',
    daysAhead: 8,
    time: '19:00',
    duration: '2h 00m',
    price: 350,
    totalSeats: 40,
    image: baseImages.sports[0],
  },
  {
    name: 'Tamil Thespians: Silapathikaram Stage Drama',
    description: 'Classic Tamil epic adapted for contemporary theatre with classical instruments and poetic dialogue delivery.',
    category: 'Theatre',
    genre: 'Classical Drama',
    language: 'Tamil',
    city: 'Chennai',
    venue: 'Kalakshetra Foundation, Thiruvanmiyur',
    daysAhead: 15,
    time: '19:00',
    duration: '2h 15m',
    price: 400,
    totalSeats: 35,
    image: baseImages.theatre[2],
  },
  {
    name: 'IIT Madras Saarang: Collegiate Music & Culture Fest',
    description: 'South India’s premier college fest featuring Battle of Bands, choreography wars, and celebrated headliners.',
    category: 'College Event',
    genre: 'Campus Festival',
    language: 'English/Tamil',
    city: 'Chennai',
    venue: 'Open Air Theatre (OAT), IIT Madras Campus',
    daysAhead: 20,
    time: '17:30',
    duration: '4h 00m',
    price: 300,
    totalSeats: 50,
    image: baseImages.college[1],
  },

  // ===================== 6. KOLKATA (5 events) =====================
  {
    name: 'Pather Panchali: 4K Restored Ray Classic Showcase',
    description: 'Satyajit Ray’s timeless lyrical masterpiece restored in 4K by Criterion with introduction by film historians.',
    category: 'Movie',
    genre: 'Classic / Drama',
    language: 'Bengali',
    city: 'Kolkata',
    venue: 'Nandan Cinema Hall 1, Rabindra Sadan Complex',
    daysAhead: 5,
    time: '17:45',
    duration: '2h 15m',
    price: 250,
    totalSeats: 35,
    image: baseImages.movie[0],
  },
  {
    name: 'Kolkata Baul & Rabindra Sangeet Melange',
    description: 'Acoustic evening connecting mystical Baul folk philosophy with soulful Rabindrasangeet melodies.',
    category: 'Concert',
    genre: 'Folk / Rabindrasangeet',
    language: 'Bengali',
    city: 'Kolkata',
    venue: 'Nazrul Mancha, Southern Avenue',
    daysAhead: 9,
    time: '18:30',
    duration: '2h 30m',
    price: 450,
    totalSeats: 40,
    image: baseImages.concert[0],
  },
  {
    name: 'Kolkata Derby: East Bengal vs Mohun Bagan Friendly',
    description: 'The iconic 100-year football rivalry witnessed live with passionate sea of red-and-gold and green-and-maroon supporters.',
    category: 'Sports',
    genre: 'Football',
    language: 'Bengali/English',
    city: 'Kolkata',
    venue: 'Salt Lake Stadium (Vivekananda Yuba Bharati Krirangan)',
    daysAhead: 14,
    time: '19:00',
    duration: '2h 00m',
    price: 500,
    totalSeats: 50,
    image: baseImages.sports[1],
  },
  {
    name: 'Shambhu Mitra Drama Legacy: Char Adhyay',
    description: 'Rabindranath Tagore’s socio-political novel presented by acclaimed Kolkata theatre collective Bohurupee.',
    category: 'Theatre',
    genre: 'Literary Drama',
    language: 'Bengali',
    city: 'Kolkata',
    venue: 'Academy of Fine Arts, Cathedral Road',
    daysAhead: 7,
    time: '18:30',
    duration: '2h 10m',
    price: 300,
    totalSeats: 35,
    image: baseImages.theatre[0],
  },
  {
    name: 'Kolkata Autumn Art & Durga Puja Cultural Gala',
    description: 'Celebration of clay art artisans, dhak percussion performances, and award-winning cultural installations.',
    category: 'Cultural',
    genre: 'Festival',
    language: 'Bengali/English',
    city: 'Kolkata',
    venue: 'Rabindra Tirtha, New Town',
    daysAhead: 22,
    time: '16:00',
    duration: '5h 00m',
    price: 350,
    totalSeats: 40,
    image: baseImages.festival[1],
  },

  // ===================== 7. PUNE (5 events) =====================
  {
    name: 'Sairat: Special 70mm Screen Celebration',
    description: 'Nagraj Manjule’s milestone Marathi love story screening with live orchestral score snippets.',
    category: 'Movie',
    genre: 'Romantic Drama',
    language: 'Marathi',
    city: 'Pune',
    venue: 'PVR City Pride, Kothrud',
    daysAhead: 3,
    time: '19:00',
    duration: '2h 45m',
    price: 280,
    totalSeats: 40,
    image: baseImages.movie[1],
  },
  {
    name: 'Sawai Gandharva Classical Hindustani Sangeet',
    description: 'Pre-festival twilight raga recital by top vocalists of the Kirana, Gwalior, and Jaipur-Atrauli gharanas.',
    category: 'Concert',
    genre: 'Hindustani Classical',
    language: 'Hindi/Marathi',
    city: 'Pune',
    venue: 'Bal Gandharva Ranga Mandir, Shivajinagar',
    daysAhead: 11,
    time: '17:30',
    duration: '3h 00m',
    price: 600,
    totalSeats: 45,
    image: baseImages.concert[1],
  },
  {
    name: 'Maharashtra Table Tennis Super League',
    description: 'Blistering fast table tennis championship playoffs featuring national squad athletes.',
    category: 'Sports',
    genre: 'Table Tennis',
    language: 'Marathi/English',
    city: 'Pune',
    venue: 'Shree Shiv Chhatrapati Sports Complex, Balewadi',
    daysAhead: 8,
    time: '15:00',
    duration: '3h 00m',
    price: 300,
    totalSeats: 35,
    image: baseImages.sports[2],
  },
  {
    name: 'Marathi Natak: Ghashiram Kotwal Tribute',
    description: 'Vijay Tendulkar’s legendary musical play blending folk dashavatara theatre with incisive political satire.',
    category: 'Theatre',
    genre: 'Political Satire',
    language: 'Marathi',
    city: 'Pune',
    venue: 'Yashwantrao Chavan Natyagruha, Kothrud',
    daysAhead: 6,
    time: '19:30',
    duration: '2h 30m',
    price: 350,
    totalSeats: 40,
    image: baseImages.theatre[1],
  },
  {
    name: 'Pune Comedy Circuit: Puneri Punsters Live',
    description: 'Witty Marathi and Hinglish observational stand-up dissecting Pune traffic, lifestyle, and nostalgic quirks.',
    category: 'Comedy',
    genre: 'Regional Stand-up',
    language: 'Marathi/Hinglish',
    city: 'Pune',
    venue: 'Classic Rock Coffee Co., Kalyani Nagar',
    daysAhead: 4,
    time: '20:00',
    duration: '1h 30m',
    price: 399,
    totalSeats: 30,
    image: baseImages.comedy[2],
  },

  // ===================== 8. AHMEDABAD (5 events) =====================
  {
    name: 'Hellaro: National Award Winning Musical Feast',
    description: 'Vibrant Gujarati period drama celebrating feminine freedom, folklore garba choreography, and Kutch culture.',
    category: 'Movie',
    genre: 'Folklore / Drama',
    language: 'Gujarati',
    city: 'Ahmedabad',
    venue: 'Cinepolis Ahmedabad One, Vastrapur',
    daysAhead: 6,
    time: '18:15',
    duration: '2h 20m',
    price: 290,
    totalSeats: 40,
    image: baseImages.movie[2],
  },
  {
    name: 'Navratri Dandiya & Garba Mega Night Live',
    description: 'Sensational live dhol beats, traditional Gujarati vocalists, and thousands celebrating in festive attire.',
    category: 'Cultural',
    genre: 'Festival / Folk',
    language: 'Gujarati',
    city: 'Ahmedabad',
    venue: 'GMDC Ground, Helmet Circle, Memnagar',
    daysAhead: 13,
    time: '20:00',
    duration: '4h 00m',
    price: 799,
    totalSeats: 60,
    image: baseImages.festival[0],
  },
  {
    name: 'Gujarat Cricket Super League: T20 Clash',
    description: 'High-octane T20 match at the world’s largest cricket venue with stunning LED light installations.',
    category: 'Sports',
    genre: 'Cricket',
    language: 'Hindi/Gujarati',
    city: 'Ahmedabad',
    venue: 'Narendra Modi Stadium, Motera',
    daysAhead: 10,
    time: '19:30',
    duration: '3h 30m',
    price: 600,
    totalSeats: 50,
    image: baseImages.sports[1],
  },
  {
    name: 'Gujju Bhai Comedy Night: Siddharth Randeria Live',
    description: 'Legendary Gujarati comic playwright in a live laughter-filled interactive comedy masterclass.',
    category: 'Comedy',
    genre: 'Stage Comedy',
    language: 'Gujarati',
    city: 'Ahmedabad',
    venue: 'Tagore Memorial Hall, Paldi',
    daysAhead: 7,
    time: '20:30',
    duration: '2h 00m',
    price: 499,
    totalSeats: 45,
    image: baseImages.comedy[0],
  },
  {
    name: 'Vibrant Gujarat FinTech & Startup Summit',
    description: 'Founders and angel syndicates discuss cross-border payments, GIFT City regulatory sandboxes, and AI fintech.',
    category: 'Conference',
    genre: 'Fintech & Startups',
    language: 'English',
    city: 'Ahmedabad',
    venue: 'Mahatma Mandir Convention Centre, Gandhinagar',
    daysAhead: 17,
    time: '09:30',
    duration: '7h 30m',
    price: 1400,
    totalSeats: 40,
    image: baseImages.conference[1],
  },

  // ===================== 9. JAIPUR (5 events) =====================
  {
    name: 'Padmaavat: Royal Palace 70mm Retrospective',
    description: 'Sanjay Leela Bhansali’s visual spectacle screened in the historic heart of Rajasthan with royal ambience.',
    category: 'Movie',
    genre: 'Historical Romance',
    language: 'Hindi',
    city: 'Jaipur',
    venue: 'Raj Mandir Cinema, Bhagwan Das Road',
    daysAhead: 4,
    time: '18:30',
    duration: '2h 45m',
    price: 350,
    totalSeats: 40,
    image: baseImages.movie[3],
  },
  {
    name: 'Rajasthan Desert Folk & Kalbelia Symphony',
    description: 'Authentic Manganiyar and Langa musicians perform soulful desert ragas, kamaicha strings, and acrobatic fire dances.',
    category: 'Concert',
    genre: 'Rajasthani Folk',
    language: 'Marwari/Hindi',
    city: 'Jaipur',
    venue: 'Jawahar Kala Kendra, Jhalana Doongri',
    daysAhead: 9,
    time: '19:00',
    duration: '2h 15m',
    price: 550,
    totalSeats: 35,
    image: baseImages.concert[2],
  },
  {
    name: 'Jaipur Polo Cup: Royal Exhibition Match',
    description: 'Gentlemanly equestrian polo match under clear blue skies with heritage hospitality and equestrian drills.',
    category: 'Sports',
    genre: 'Polo / Equestrian',
    language: 'English/Hindi',
    city: 'Jaipur',
    venue: 'Rajasthan Polo Club Grounds, Rambagh',
    daysAhead: 15,
    time: '15:30',
    duration: '2h 30m',
    price: 800,
    totalSeats: 30,
    image: baseImages.sports[3],
  },
  {
    name: 'Pink City Stand-up Special: Royal Roasts',
    description: 'Fresh sharp comedy tackling modern Rajasthani youth, wedding culture, and startup ambitions.',
    category: 'Comedy',
    genre: 'Stand-up',
    language: 'Hindi',
    city: 'Jaipur',
    venue: 'Birla Auditorium, Statue Circle',
    daysAhead: 7,
    time: '20:00',
    duration: '1h 30m',
    price: 399,
    totalSeats: 35,
    image: baseImages.comedy[1],
  },
  {
    name: 'Jaipur Puppet & Storytelling Heritage Festival',
    description: 'Master puppeteers showcase traditional Kathputli theatre, folklore tales of warriors, and interactive child workshops.',
    category: 'Family',
    genre: 'Puppetry & Storytelling',
    language: 'Hindi',
    city: 'Jaipur',
    venue: 'Albert Hall Museum Courtyard, Ram Niwas Garden',
    daysAhead: 12,
    time: '16:00',
    duration: '2h 30m',
    price: 250,
    totalSeats: 35,
    image: baseImages.family[1],
  },

  // ===================== 10. CHANDIGARH (5 events) =====================
  {
    name: 'Carry On Jatta 3: Special Family Screening',
    description: 'The record-breaking Punjabi comedy laugh riot screened with Dolby surround sound and recliner seating.',
    category: 'Movie',
    genre: 'Comedy',
    language: 'Punjabi',
    city: 'Chandigarh',
    venue: 'PVR Elante Mall, Industrial Area Phase 1',
    daysAhead: 5,
    time: '19:15',
    duration: '2h 15m',
    price: 320,
    totalSeats: 40,
    image: baseImages.movie[4],
  },
  {
    name: 'Diljit & Punjabi Virsa Live: Bhangra Storm',
    description: 'High-octane Punjabi pop and traditional folk rhythms featuring live dholis, chimta rhythms, and modern synths.',
    category: 'Concert',
    genre: 'Punjabi Pop / Folk',
    language: 'Punjabi',
    city: 'Chandigarh',
    venue: 'Sector 17 Plaza Amphitheatre',
    daysAhead: 11,
    time: '18:30',
    duration: '3h 30m',
    price: 899,
    totalSeats: 50,
    image: baseImages.concert[3],
  },
  {
    name: 'North Zone Inter-State Tennis Championship',
    description: 'Junior and senior hardcourt tennis tournament featuring promising athletes across Punjab, Haryana, and HP.',
    category: 'Sports',
    genre: 'Tennis',
    language: 'English',
    city: 'Chandigarh',
    venue: 'CLTA Tennis Stadium, Sector 10',
    daysAhead: 8,
    time: '16:00',
    duration: '3h 00m',
    price: 250,
    totalSeats: 35,
    image: baseImages.sports[2],
  },
  {
    name: 'Laughter Gedi: Punjabi Stand-up Tour',
    description: 'Hilarious observational humor exploring university life, Chandigarh roundabouts, and NRI cousin weddings.',
    category: 'Comedy',
    genre: 'Stand-up',
    language: 'Punjabi/Hindi',
    city: 'Chandigarh',
    venue: 'Tagore Theatre, Sector 18',
    daysAhead: 6,
    time: '19:30',
    duration: '1h 45m',
    price: 450,
    totalSeats: 40,
    image: baseImages.comedy[2],
  },
  {
    name: 'Panjab University Aagaz: Youth Cultural Festival',
    description: 'Inter-college showdown featuring Giddha, Bhangra, street plays, and rock band competitions.',
    category: 'College Event',
    genre: 'Collegiate Fest',
    language: 'Punjabi/English',
    city: 'Chandigarh',
    venue: 'Law Auditorium, Panjab University Sector 14',
    daysAhead: 18,
    time: '11:00',
    duration: '6h 00m',
    price: 200,
    totalSeats: 40,
    image: baseImages.college[0],
  },

  // ===================== 11. KOCHI (5 events) =====================
  {
    name: 'Manjummel Boys: Special 4K Atmos Screening',
    description: 'Gripping real-life survival thriller celebrating Kerala brotherhood with sublime audio-visual fidelity.',
    category: 'Movie',
    genre: 'Survival / Thriller',
    language: 'Malayalam',
    city: 'Kochi',
    venue: 'PVR LuLu Mall, Edappally',
    daysAhead: 3,
    time: '18:45',
    duration: '2h 20m',
    price: 300,
    totalSeats: 40,
    image: baseImages.movie[0],
  },
  {
    name: 'Thaikkudam Bridge: Live Fusion Rock Experience',
    description: 'Iconic Kerala band blending progressive rock, Malayalam folk anthems, violin harmonies, and heavy drums.',
    category: 'Concert',
    genre: 'Fusion Rock',
    language: 'Malayalam/English',
    city: 'Kochi',
    venue: 'Jawaharlal Nehru International Stadium Ground, Kaloor',
    daysAhead: 10,
    time: '19:00',
    duration: '3h 00m',
    price: 799,
    totalSeats: 50,
    image: baseImages.concert[4],
  },
  {
    name: 'Kerala Blasters vs Bengaluru FC: Southern Derby',
    description: 'The deafening yellow sea erupts in one of Indian football’s most passionate rivalry games.',
    category: 'Sports',
    genre: 'Football',
    language: 'Malayalam/English',
    city: 'Kochi',
    venue: 'Jawaharlal Nehru Stadium, Kaloor',
    daysAhead: 14,
    time: '19:30',
    duration: '2h 00m',
    price: 450,
    totalSeats: 50,
    image: baseImages.sports[0],
  },
  {
    name: 'Kathakali All-Night Classical Narrative: Duryodhana Vadham',
    description: 'Traditional Kerala temple theatre featuring elaborate facial makeup, chenda percussion, and mudra storytelling.',
    category: 'Theatre',
    genre: 'Classical Kathakali',
    language: 'Malayalam/Sanskrit',
    city: 'Kochi',
    venue: 'Kerala Kathakali Centre, Fort Kochi',
    daysAhead: 7,
    time: '18:30',
    duration: '2h 45m',
    price: 500,
    totalSeats: 30,
    image: baseImages.theatre[2],
  },
  {
    name: 'Kochi-Muziris Contemporary Art & Culture Showcase',
    description: 'International installation art, experimental photography, sea pavilions, and artisanal spice food trail.',
    category: 'Cultural',
    genre: 'Art & Culture',
    language: 'Multilingual',
    city: 'Kochi',
    venue: 'Aspinwall House, Fort Kochi',
    daysAhead: 21,
    time: '10:00',
    duration: '6h 00m',
    price: 350,
    totalSeats: 35,
    image: baseImages.festival[1],
  },

  // ===================== 12. LUCKNOW (5 events) =====================
  {
    name: 'Umrao Jaan: Restored Classic Awadh Screening',
    description: 'Muzaffar Ali’s poetic masterpiece with unforgettable ghazals by Khayyam and Rekha’s timeless performance.',
    category: 'Movie',
    genre: 'Period Romance',
    language: 'Hindi/Urdu',
    city: 'Lucknow',
    venue: 'Wave Cinemas, Gomti Nagar',
    daysAhead: 4,
    time: '18:00',
    duration: '2h 30m',
    price: 280,
    totalSeats: 35,
    image: baseImages.movie[1],
  },
  {
    name: 'Sham-e-Awadh: Classical Thumri & Ghazal Mehfil',
    description: 'Intimate evening celebrating Lucknow gharana thumri, dadra, and soulful ghazals with harmonium and sarangi.',
    category: 'Concert',
    genre: 'Ghazal / Thumri',
    language: 'Urdu/Hindi',
    city: 'Lucknow',
    venue: 'Sangeet Natak Akademi, Gomti Nagar',
    daysAhead: 8,
    time: '19:00',
    duration: '2h 15m',
    price: 500,
    totalSeats: 40,
    image: baseImages.concert[0],
  },
  {
    name: 'Syed Modi International Badminton Championship',
    description: 'BWF World Tour Super 300 international badminton championship action with top world shuttlers.',
    category: 'Sports',
    genre: 'Badminton',
    language: 'English/Hindi',
    city: 'Lucknow',
    venue: 'Babu Banarasi Das Indoor Stadium',
    daysAhead: 12,
    time: '15:00',
    duration: '3h 30m',
    price: 400,
    totalSeats: 40,
    image: baseImages.sports[1],
  },
  {
    name: 'Dastangoi: The Ancient Art of Urdu Storytelling',
    description: 'Dastango performers bring alive tales of Tilism-e-Hoshruba and contemporary narratives through hypnotic voice modulation.',
    category: 'Theatre',
    genre: 'Oral Storytelling',
    language: 'Urdu',
    city: 'Lucknow',
    venue: 'Bhatkhande Sanskriti Vishwavidyalaya Auditorium',
    daysAhead: 6,
    time: '19:30',
    duration: '1h 45m',
    price: 350,
    totalSeats: 35,
    image: baseImages.theatre[0],
  },
  {
    name: 'Nawabi Hasya Kavi Sammelan Live',
    description: 'Satirical Hindi and Urdu poetry recital featuring veteran hasya kavis in an evening of non-stop laughter.',
    category: 'Comedy',
    genre: 'Poetic Satire / Comedy',
    language: 'Hindi/Urdu',
    city: 'Lucknow',
    venue: 'Scientific Convention Centre, Shah Mina Road',
    daysAhead: 15,
    time: '20:00',
    duration: '2h 30m',
    price: 350,
    totalSeats: 40,
    image: baseImages.comedy[0],
  },

  // ===================== 13. INDORE (5 events) =====================
  {
    name: 'Stree 2: Horror-Comedy IMAX Screening',
    description: 'The blockbuster horror-comedy sensation with booming surround audio and vibrant crowd reactions.',
    category: 'Movie',
    genre: 'Horror / Comedy',
    language: 'Hindi',
    city: 'Indore',
    venue: 'PVR Treasure Island, MG Road',
    daysAhead: 3,
    time: '19:30',
    duration: '2h 25m',
    price: 290,
    totalSeats: 40,
    image: baseImages.movie[2],
  },
  {
    name: 'Indore Food & Music Carnival',
    description: 'Celebrating Sarafa Bazaar flavors alongside live indie acoustics and DJ dance tents under the stars.',
    category: 'Cultural',
    genre: 'Culinary & Music',
    language: 'Hindi',
    city: 'Indore',
    venue: 'Dussehra Maidan, Annapurna Road',
    daysAhead: 9,
    time: '17:00',
    duration: '5h 00m',
    price: 450,
    totalSeats: 50,
    image: baseImages.festival[0],
  },
  {
    name: 'MP Cricket League Championship Final',
    description: 'Inter-district T20 cricket finale between Indore Royals and Bhopal Blasters at historic Holkar Stadium.',
    category: 'Sports',
    genre: 'Cricket',
    language: 'Hindi',
    city: 'Indore',
    venue: 'Holkar Cricket Stadium, Race Course Road',
    daysAhead: 13,
    time: '19:00',
    duration: '3h 30m',
    price: 400,
    totalSeats: 45,
    image: baseImages.sports[3],
  },
  {
    name: 'Zakir Khan: Live in Indore Homecoming Tour',
    description: 'The Sakht Launda returns to his hometown for an emotional, hilarious two-hour special set.',
    category: 'Comedy',
    genre: 'Stand-up',
    language: 'Hindi',
    city: 'Indore',
    venue: 'Abhay Prashal Indoor Stadium, Race Course Road',
    daysAhead: 7,
    time: '20:00',
    duration: '2h 00m',
    price: 799,
    totalSeats: 50,
    image: baseImages.comedy[1],
  },
  {
    name: 'IIM Indore IRIS: Management & Cultural Festival',
    description: 'Central India’s premier B-school festival featuring corporate case challenges, comedy nights, and celebrity rock shows.',
    category: 'College Event',
    genre: 'Management Fest',
    language: 'English',
    city: 'Indore',
    venue: 'IIM Indore Campus Auditorium, Rau',
    daysAhead: 19,
    time: '10:00',
    duration: '7h 00m',
    price: 300,
    totalSeats: 40,
    image: baseImages.college[1],
  },

  // ===================== 14. BHOPAL (5 events) =====================
  {
    name: 'Paan Singh Tomar: Tribute Screening',
    description: 'Tigmanshu Dhulia’s gripping Chambal biographical thriller starring Irrfan Khan screened with special panel discussion.',
    category: 'Movie',
    genre: 'Biographical Drama',
    language: 'Hindi',
    city: 'Bhopal',
    venue: 'Cinepolis DB City Mall, MP Nagar',
    daysAhead: 5,
    time: '18:15',
    duration: '2h 20m',
    price: 250,
    totalSeats: 35,
    image: baseImages.movie[3],
  },
  {
    name: 'Bhopal Lake Twilight Jazz & Fusion Night',
    description: 'Relaxing saxophone melodies, upright bass grooves, and piano improvisations overlooking the tranquil Upper Lake.',
    category: 'Concert',
    genre: 'Jazz / Fusion',
    language: 'Instrumental',
    city: 'Bhopal',
    venue: 'Bharat Bhavan Open Amphitheatre, Shamla Hills',
    daysAhead: 10,
    time: '18:30',
    duration: '2h 15m',
    price: 450,
    totalSeats: 35,
    image: baseImages.concert[1],
  },
  {
    name: 'National Canoe & Kayaking Championship',
    description: 'Thrilling water-sports racing featuring state champions paddling on the scenic waters of Upper Lake.',
    category: 'Sports',
    genre: 'Water Sports / Kayaking',
    language: 'Hindi/English',
    city: 'Bhopal',
    venue: 'Upper Lake Boat Club, Shamla Hills',
    daysAhead: 14,
    time: '09:00',
    duration: '4h 00m',
    price: 200,
    totalSeats: 35,
    image: baseImages.sports[0],
  },
  {
    name: 'Rangmandal Drama: Habib Tanvir’s Charandas Chor',
    description: 'Naya Theatre performs the historic folk play with authentic tribal Chhattisgarhi actors, folk songs, and humor.',
    category: 'Theatre',
    genre: 'Folk Theatre',
    language: 'Hindi/Chhattisgarhi',
    city: 'Bhopal',
    venue: 'Antarang Hall, Bharat Bhavan',
    daysAhead: 8,
    time: '19:00',
    duration: '2h 10m',
    price: 300,
    totalSeats: 35,
    image: baseImages.theatre[1],
  },
  {
    name: 'Madhya Pradesh Tribal Art & Craft Heritage Fair',
    description: 'Gond and Bhil painting masterclasses, terracotta art stalls, and authentic Mahua forest culinary tastings.',
    category: 'Cultural',
    genre: 'Tribal Culture',
    language: 'Hindi',
    city: 'Bhopal',
    venue: 'Madhya Pradesh Tribal Museum, Shyamala Hills',
    daysAhead: 16,
    time: '11:00',
    duration: '6h 00m',
    price: 250,
    totalSeats: 40,
    image: baseImages.festival[1],
  },

  // ===================== 15. BHUBANESWAR (5 events) =====================
  {
    name: 'Daman: Special 4K Odia Feature Presentation',
    description: 'Critically acclaimed Odia medical drama depicting a doctor’s relentless fight against malaria in remote tribal pockets.',
    category: 'Movie',
    genre: 'Drama',
    language: 'Odia',
    city: 'Bhubaneswar',
    venue: 'Cinepolis Esplanade One Mall, Rasulgarh',
    daysAhead: 4,
    time: '18:30',
    duration: '2h 15m',
    price: 260,
    totalSeats: 40,
    image: baseImages.movie[4],
  },
  {
    name: 'Mukteswar Odissi Sangeet & Dance Festival',
    description: 'Internationally renowned Odissi dancers perform against the illuminated 10th-century stone temple facade.',
    category: 'Concert',
    genre: 'Odissi Classical Dance & Music',
    language: 'Odia/Sanskrit',
    city: 'Bhubaneswar',
    venue: 'Mukteswar Temple Complex, Old Town',
    daysAhead: 11,
    time: '18:00',
    duration: '3h 00m',
    price: 400,
    totalSeats: 35,
    image: baseImages.concert[2],
  },
  {
    name: 'Kalinga Super Cup Hockey Championship',
    description: 'Fast, high-adrenaline international field hockey under stadium lights at India’s premier hockey cathedral.',
    category: 'Sports',
    genre: 'Field Hockey',
    language: 'English/Odia',
    city: 'Bhubaneswar',
    venue: 'Kalinga Stadium Hockey Complex, Nayapalli',
    daysAhead: 15,
    time: '19:30',
    duration: '2h 00m',
    price: 350,
    totalSeats: 45,
    image: baseImages.sports[1],
  },
  {
    name: 'Bhubaneswar Stand-up Spotlight: Utkal Humor',
    description: 'Bilingual Odia and English stand-up comedy exploring hostel life, Puri beach memories, and IT corridors.',
    category: 'Comedy',
    genre: 'Stand-up',
    language: 'Odia/English',
    city: 'Bhubaneswar',
    venue: 'Rabindra Mandap, Unit IV',
    daysAhead: 7,
    time: '19:30',
    duration: '1h 30m',
    price: 350,
    totalSeats: 35,
    image: baseImages.comedy[2],
  },
  {
    name: 'Konark Sun & Heritage Cultural Showcase',
    description: 'A grand evening of classical dance recitals, sand art exhibitions by Padma Shri sculptors, and handloom expos.',
    category: 'Cultural',
    genre: 'Heritage & Dance',
    language: 'Multilingual',
    city: 'Bhubaneswar',
    venue: 'Utkal Mandap, State Museum Compound',
    daysAhead: 20,
    time: '17:00',
    duration: '4h 00m',
    price: 300,
    totalSeats: 40,
    image: baseImages.festival[0],
  },

  // ===================== 16. VISAKHAPATNAM (5 events) =====================
  {
    name: 'Hanu-Man: Telugu Super-Hero 70mm Experience',
    description: 'Prasanth Varma’s Indian superhero visual spectacle with crystal clear digital cinema presentation.',
    category: 'Movie',
    genre: 'Mythological Action',
    language: 'Telugu',
    city: 'Visakhapatnam',
    venue: 'Inox Varun Beach, Beach Road',
    daysAhead: 3,
    time: '18:45',
    duration: '2h 35m',
    price: 300,
    totalSeats: 40,
    image: baseImages.movie[0],
  },
  {
    name: 'Vizag Bay Acoustic & Beachside Indie Fest',
    description: 'Live seaside music stage with sea breezes, acoustic guitars, Telugu indie fusion, and chilled atmosphere.',
    category: 'Concert',
    genre: 'Acoustic / Indie',
    language: 'Telugu/English',
    city: 'Visakhapatnam',
    venue: 'RK Beach Open Amphitheatre, Pandurangapuram',
    daysAhead: 8,
    time: '18:30',
    duration: '3h 00m',
    price: 499,
    totalSeats: 40,
    image: baseImages.concert[3],
  },
  {
    name: 'East Coast Volleyball Championship Finals',
    description: 'Spirited beach and indoor volleyball spikes and saves by leading university teams.',
    category: 'Sports',
    genre: 'Volleyball',
    language: 'Telugu/English',
    city: 'Visakhapatnam',
    venue: 'Swarna Bharathi Indoor Stadium, Resapuvanipalem',
    daysAhead: 12,
    time: '16:30',
    duration: '2h 30m',
    price: 250,
    totalSeats: 35,
    image: baseImages.sports[2],
  },
  {
    name: 'Andhra Comedy Waves: Vizag Stand-up Club',
    description: 'Laugh out loud with humorous regional tales about Vizag steel plant townships, vizag slang, and coastal life.',
    category: 'Comedy',
    genre: 'Stand-up',
    language: 'Telugu',
    city: 'Visakhapatnam',
    venue: 'Gurajada Kalakshetram, Siripuram',
    daysAhead: 6,
    time: '20:00',
    duration: '1h 30m',
    price: 350,
    totalSeats: 35,
    image: baseImages.comedy[0],
  },
  {
    name: 'Circus of Wonders: Spectacular Family Carnival',
    description: 'Aerial silk acrobats, juggling phenoms, comic clowns, and dazzling laser lights for families.',
    category: 'Family',
    genre: 'Circus & Acrobats',
    language: 'Non-verbal / English',
    city: 'Visakhapatnam',
    venue: 'Andhra University Grounds, Waltair',
    daysAhead: 16,
    time: '17:00',
    duration: '2h 15m',
    price: 350,
    totalSeats: 45,
    image: baseImages.family[0],
  },

  // ===================== 17. VIJAYAWADA (5 events) =====================
  {
    name: 'Baahubali: The Conclusion Retrospective',
    description: 'SS Rajamouli’s historical spectacle returns with thunderous 7.1 audio and grand visual master print.',
    category: 'Movie',
    genre: 'Historical Action',
    language: 'Telugu',
    city: 'Vijayawada',
    venue: 'PVR Ripples Mall, MG Road',
    daysAhead: 4,
    time: '19:00',
    duration: '2h 50m',
    price: 280,
    totalSeats: 40,
    image: baseImages.movie[1],
  },
  {
    name: 'Krishna Tarang: Telugu Folk & Percussion Ensemble',
    description: 'Celebration of traditional Janapada geetalu, dappu drums, and flute melodies honoring river Krishna.',
    category: 'Concert',
    genre: 'Telugu Folk',
    language: 'Telugu',
    city: 'Vijayawada',
    venue: 'Tummalapalli Kalakshetram, Suryaraopeta',
    daysAhead: 9,
    time: '18:30',
    duration: '2h 15m',
    price: 350,
    totalSeats: 35,
    image: baseImages.concert[4],
  },
  {
    name: 'AP Badminton League Championship',
    description: 'Exciting regional badminton tournament featuring top seeded state athletes.',
    category: 'Sports',
    genre: 'Badminton',
    language: 'Telugu/English',
    city: 'Vijayawada',
    venue: 'Dandavadi Indoor Stadium, Labbipet',
    daysAhead: 13,
    time: '15:30',
    duration: '3h 00m',
    price: 250,
    totalSeats: 35,
    image: baseImages.sports[3],
  },
  {
    name: 'Telugu Natakam: Kanyasulkam Revival',
    description: 'Gurajada Apparao’s groundbreaking social reform play revived with stellar cast and humorous classic dialogues.',
    category: 'Theatre',
    genre: 'Social Satire',
    language: 'Telugu',
    city: 'Vijayawada',
    venue: 'Ghantasala Venkateswara Rao Government Music College Hall',
    daysAhead: 7,
    time: '19:00',
    duration: '2h 30m',
    price: 300,
    totalSeats: 35,
    image: baseImages.theatre[2],
  },
  {
    name: 'Vijayawada Clean Energy & Tech Summit 2026',
    description: 'Engineers, renewable power developers, and solar pioneers discuss Andhra Pradesh’s green energy transition.',
    category: 'Conference',
    genre: 'Clean Energy & Technology',
    language: 'English/Telugu',
    city: 'Vijayawada',
    venue: 'A-Convention Centre, MG Road',
    daysAhead: 17,
    time: '09:30',
    duration: '7h 00m',
    price: 850,
    totalSeats: 35,
    image: baseImages.conference[0],
  },

  // ===================== 18. GOA (5 events) =====================
  {
    name: 'Goa International Short Film Showcase',
    description: 'Curated international indie short films and award-winning Konkani docu-dramas with filmmaker panels.',
    category: 'Movie',
    genre: 'Indie Shorts',
    language: 'Konkani/English',
    city: 'Goa',
    venue: 'Maquinez Palace Cinema, ESG Complex, Panaji',
    daysAhead: 5,
    time: '18:00',
    duration: '2h 30m',
    price: 350,
    totalSeats: 35,
    image: baseImages.movie[2],
  },
  {
    name: 'Goa Sunset Sunset Electronic Beach Fest',
    description: 'Deep house, melodic techno, and sunset ambient electronica on the sands with international and local DJs.',
    category: 'Concert',
    genre: 'EDM / Electronic',
    language: 'Instrumental',
    city: 'Goa',
    venue: 'Vagator Beach Arena, North Goa',
    daysAhead: 10,
    time: '17:00',
    duration: '5h 00m',
    price: 1200,
    totalSeats: 50,
    image: baseImages.concert[0],
  },
  {
    name: 'Goa Pro League Football Derby',
    description: 'Fast coastal football clash between Churchill Brothers and Dempo SC with lively brass bands in the stands.',
    category: 'Sports',
    genre: 'Football',
    language: 'English/Konkani',
    city: 'Goa',
    venue: 'Fatorda Stadium (Jawaharlal Nehru Stadium), Margao',
    daysAhead: 14,
    time: '16:30',
    duration: '2h 00m',
    price: 300,
    totalSeats: 40,
    image: baseImages.sports[0],
  },
  {
    name: 'Goa Carnival Carnival Parade & Cultural Extravaganza',
    description: 'King Momo declares festivities with colorful street floats, brass bands, fado singers, and festive masquerades.',
    category: 'Cultural',
    genre: 'Carnival Festival',
    language: 'Konkani/English',
    city: 'Goa',
    venue: 'Dayanand Bandodkar Marg, Panaji',
    daysAhead: 18,
    time: '16:00',
    duration: '4h 00m',
    price: 400,
    totalSeats: 40,
    image: baseImages.festival[0],
  },
  {
    name: 'Tiatr Festival: Classic Konkani Musical Comedy',
    description: 'Traditional Goan theatrical tiatr filled with satirical cantos, social morals, and side-splitting comedy.',
    category: 'Theatre',
    genre: 'Musical Comedy (Tiatr)',
    language: 'Konkani',
    city: 'Goa',
    venue: 'Kala Academy Open Complex, Campal, Panaji',
    daysAhead: 8,
    time: '19:30',
    duration: '2h 30m',
    price: 300,
    totalSeats: 35,
    image: baseImages.theatre[0],
  },

  // ===================== 19. PATNA (5 events) =====================
  {
    name: 'Gangs of Wasseypur: 4K Director Cut Double Bill',
    description: 'Anurag Kashyap’s gritty crime masterpiece presented with crisp digital master and roaring auditorium audio.',
    category: 'Movie',
    genre: 'Crime / Drama',
    language: 'Hindi',
    city: 'Patna',
    venue: 'Cinepolis Patna One Mall, Exhibition Road',
    daysAhead: 4,
    time: '18:00',
    duration: '3h 10m',
    price: 250,
    totalSeats: 40,
    image: baseImages.movie[3],
  },
  {
    name: 'Bhojpuri & Maithili Folk Rhythms Live',
    description: 'Soulful Kajari, Chaiti, and classical Maithili melodies accompanied by dholak, harmonium, and flute.',
    category: 'Concert',
    genre: 'Folk / Classical',
    language: 'Bhojpuri/Maithili',
    city: 'Patna',
    venue: 'Premchand Rangshala, Rajendra Nagar',
    daysAhead: 9,
    time: '18:30',
    duration: '2h 15m',
    price: 300,
    totalSeats: 35,
    image: baseImages.concert[1],
  },
  {
    name: 'Bihar State Kabaddi Premier League',
    description: 'Electrifying physical raids, tactical ankle holds, and super tackles in state-level championship tournament.',
    category: 'Sports',
    genre: 'Kabaddi',
    language: 'Hindi',
    city: 'Patna',
    venue: 'Patliputra Sports Complex, Kankarbagh',
    daysAhead: 13,
    time: '17:00',
    duration: '2h 30m',
    price: 250,
    totalSeats: 40,
    image: baseImages.sports[1],
  },
  {
    name: 'Patna Laughter Junction: Stand-up Specials',
    description: 'Witty observational comedy covering civil service exams preparation, wedding traditions, and local satire.',
    category: 'Comedy',
    genre: 'Stand-up',
    language: 'Hindi/Bhojpuri',
    city: 'Patna',
    venue: 'SK Memorial Hall, Gandhi Maidan',
    daysAhead: 6,
    time: '19:30',
    duration: '1h 45m',
    price: 350,
    totalSeats: 40,
    image: baseImages.comedy[1],
  },
  {
    name: 'Patna Planetarium Stargazing & Cosmic Wonder Night',
    description: 'Fascinating dome projections on black holes, moon craters, and telescope stargazing session on the lawns.',
    category: 'Family',
    genre: 'Astronomy & Science',
    language: 'Hindi/English',
    city: 'Patna',
    venue: 'Indira Gandhi Planetarium (Taramandal), Bailey Road',
    daysAhead: 16,
    time: '17:30',
    duration: '2h 00m',
    price: 200,
    totalSeats: 35,
    image: baseImages.family[1],
  },

  // ===================== 20. GUWAHATI (5 events) =====================
  {
    name: 'Village Rockstars: Rima Das Masterpiece 4K',
    description: 'National award winning lyrical Assamese drama screened with Director Q&A and authentic village soundtrack.',
    category: 'Movie',
    genre: 'Drama / Indie',
    language: 'Assamese',
    city: 'Guwahati',
    venue: 'PVR City Centre Mall, GS Road',
    daysAhead: 4,
    time: '18:15',
    duration: '1h 50m',
    price: 250,
    totalSeats: 35,
    image: baseImages.movie[4],
  },
  {
    name: 'Bihu Beats & Northeast Indie Rock Fusion',
    description: 'Pepa horns, dhol beats, and electric guitars unite in an energetic festival celebrating modern Assamese music.',
    category: 'Concert',
    genre: 'Assamese Folk / Rock',
    language: 'Assamese/English',
    city: 'Guwahati',
    venue: 'Sarusajai Stadium Amphitheatre, Lokhra',
    daysAhead: 9,
    time: '18:00',
    duration: '3h 30m',
    price: 550,
    totalSeats: 45,
    image: baseImages.concert[2],
  },
  {
    name: 'Northeast Inter-State Football Championship',
    description: 'Fast-paced, technically gifted regional football rivalry between Assam and Manipur.',
    category: 'Sports',
    genre: 'Football',
    language: 'Assamese/English',
    city: 'Guwahati',
    venue: 'Indira Gandhi Athletic Stadium, Sarusajai',
    daysAhead: 13,
    time: '17:00',
    duration: '2h 00m',
    price: 300,
    totalSeats: 40,
    image: baseImages.sports[0],
  },
  {
    name: 'Brahmaputra Cultural & Heritage Showcase',
    description: 'Traditional Bihu dance troupes, Mishing weaving exhibitions, and authentic northeastern culinary pavilions.',
    category: 'Cultural',
    genre: 'Heritage Festival',
    language: 'Assamese/English',
    city: 'Guwahati',
    venue: 'Srimanta Sankaradeva Kalakshetra, Panjabari',
    daysAhead: 15,
    time: '11:00',
    duration: '5h 00m',
    price: 250,
    totalSeats: 40,
    image: baseImages.festival[1],
  },
  {
    name: 'IIT Guwahati Alcheringa: Battle of the Rock Bands',
    description: 'Northeast India’s biggest collegiate cultural festival rock arena with headline metal and acoustic acts.',
    category: 'College Event',
    genre: 'Collegiate Fest',
    language: 'English/Hindi',
    city: 'Guwahati',
    venue: 'IIT Guwahati Campus, Amingaon',
    daysAhead: 20,
    time: '17:00',
    duration: '4h 00m',
    price: 250,
    totalSeats: 40,
    image: baseImages.college[0],
  },
];

/**
 * Transforms raw events into database documents with dates and generated seats
 */
export const get100Events = () => {
  const now = Date.now();

  return rawEvents.map((item, index) => {
    const eventDate = new Date(now + item.daysAhead * 24 * 60 * 60 * 1000);
    const location = `${item.venue}, ${item.city}`;

    return {
      name: item.name,
      description: item.description,
      category: item.category,
      genre: item.genre || '',
      language: item.language || 'Multilingual',
      city: item.city,
      venue: item.venue,
      location: location,
      date: eventDate,
      time: item.time,
      duration: item.duration || '2h 00m',
      price: item.price,
      totalSeats: item.totalSeats,
      availableSeats: item.totalSeats,
      image: item.image,
    };
  });
};

export default get100Events;
